## Site metadata ##

title: Jekyll Actions Guide
description: How to setup GH Pages + GH Actions for use with Jekyll 4

### Built settings ###

url: "https://iwahle.github.io/" # "https://michaelcurrin.github.io"
baseurl: "/personal_site3"

github_username: MichaelCurrin

theme: minima
