## Site metadata ##

title: Iman Wahle
description: A site about things I am interested in!

### Built settings ###

url: "https://iwahle.github.io/"
baseurl: "/personal_site"

github_username: iwahle

theme: minima

paginate: true